version: "3.9"
services:
  pgsql:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=iampgsqlroot
      - POSTGRES_DB=clbot
      - POSTGRES_USER=clbot
    volumes:
      - "/home/user/.var/clbotpgsql:/var/lib/postgresql"
